# Generated by Django 5.1.1 on 2024-09-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baza',
            name='jami_narxi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='baza',
            name='max_kg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='baza',
            name='max_ol_narx',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='baza',
            name='max_sol_narx',
            field=models.IntegerField(default=0),
        ),
    ]
