# Generated by Django 5.1.1 on 2024-09-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0003_hisobot_baza_sana'),
    ]

    operations = [
        migrations.CreateModel(
            name='baza_hisobot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_ismi', models.CharField(max_length=30)),
                ('max_ol_narx', models.IntegerField(default=0)),
                ('max_sol_narx', models.IntegerField(default=0)),
                ('max_kg', models.IntegerField(default=0)),
                ('jami_narxi', models.IntegerField(default=0)),
                ('sana', models.CharField(max_length=30)),
            ],
        ),
    ]
