# Generated by Django 4.2.15 on 2024-09-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0006_hisobot_max_ol_narx'),
    ]

    operations = [
        migrations.CreateModel(
            name='kirish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
                ('parol', models.CharField(max_length=30)),
                ('user_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='baza',
        ),
        migrations.DeleteModel(
            name='baza_hisobot',
        ),
        migrations.DeleteModel(
            name='hisobot',
        ),
    ]
