# Generated by Django 4.2.15 on 2024-09-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0007_kirish_delete_baza_delete_baza_hisobot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='set_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.CharField(max_length=30)),
                ('rasm', models.ImageField(upload_to='images/')),
                ('video', models.FileField(upload_to='videos/')),
                ('url_tugmachalar', models.CharField(max_length=30)),
                ('vaqt_soat', models.IntegerField(default=0)),
                ('vaqt_minut', models.IntegerField(default=0)),
                ('tugash_sanasi', models.CharField(max_length=30)),
                ('xabarni_qadash', models.CharField(max_length=30)),
                ('songgi_xabarni_ochirish', models.CharField(max_length=30)),
            ],
        ),
    ]
