# Generated by Django 4.2.15 on 2024-09-19 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0008_set_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='set_message',
            name='gurux_id',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='set_message',
            name='users_id',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='set_message',
            name='xolati',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
